# Generated by Django 3.2.9 on 2021-11-22 21:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paymentMethod', models.CharField(default=0, max_length=100, verbose_name='PaymentMethod')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('createdByUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceCreatedByUserId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
