# Generated by Django 3.2.9 on 2021-11-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=0, max_length=100, verbose_name='Name')),
                ('value', models.FloatField(default=0)),
            ],
        ),
    ]
