# Generated by Django 3.2.9 on 2021-11-23 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoiceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceId', to='authApp.invoice')),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceId', to='authApp.service')),
            ],
        ),
    ]
